---

- hosts: all
  pre_tasks:
    - name: update ca-certificates package
      package:
        name: ca-certificates
        state: present
      tags:
        - skip_ansible_lint
  roles:
    - role: andrewrothstein.anaconda
      anaconda_make_sys_default: yes
