---

driver:
  name: docker

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
  playbooks:
    converge: ../../playbook.yml

platforms:
  - name: ubuntu
    image: ubuntu
    image_version: 16.04
